# Generated by Django 4.2.29 on 2026-03-19 12:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0003_blog_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='viewed_by',
            field=models.ManyToManyField(blank=True, related_name='viewed_blogs', to=settings.AUTH_USER_MODEL),
        ),
    ]
